version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_USERNAME: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - /home/duducp/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'postgres@email.com'
      PGADMIN_DEFAULT_PASSWORD: 'postgres'
    ports:
      - '15432:80'
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
